(() => {
  "use strict";
  const API_BASE = "https://172-238-20-217.ip.linodeusercontent.com/api/v1";
  const message = document.getElementById("accountMessage"), form = document.getElementById("loginForm"), submit = document.getElementById("loginSubmit");
  try { const t=localStorage.getItem("taiwan_stock_market_theme"); if(t==="light"||(!t&&matchMedia("(prefers-color-scheme: light)").matches))document.body.classList.add("theme-light"); } catch (_) {}
  document.addEventListener("click", e => { const b=e.target.closest("[data-account-view]"); if(!b)return; document.querySelectorAll("[data-account-panel]").forEach(p=>{const a=p.dataset.accountPanel===b.dataset.accountView;p.hidden=!a;p.classList.toggle("is-active",a)});message.textContent=""; });
  const decode=v=>Uint8Array.from(atob(v.replace(/-/g,"+").replace(/_/g,"/").padEnd(Math.ceil(v.length/4)*4,"=")),c=>c.charCodeAt(0));
  const encode=b=>btoa(String.fromCharCode(...new Uint8Array(b))).replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/g,"");
  function prepare(o,type){o.challenge=decode(o.challenge);if(type==="registration"){o.user.id=decode(o.user.id);(o.excludeCredentials||[]).forEach(x=>x.id=decode(x.id));}else(o.allowCredentials||[]).forEach(x=>x.id=decode(x.id));return o;}
  function serialize(c){const r={clientDataJSON:encode(c.response.clientDataJSON)};if(c.response.attestationObject){r.attestationObject=encode(c.response.attestationObject);r.transports=c.response.getTransports?c.response.getTransports():[];}else{r.authenticatorData=encode(c.response.authenticatorData);r.signature=encode(c.response.signature);r.userHandle=c.response.userHandle?encode(c.response.userHandle):null;}return{id:c.id,rawId:encode(c.rawId),type:c.type,response:r,clientExtensionResults:c.getClientExtensionResults()};}
  async function request(path,body){const c=new AbortController(),timer=setTimeout(()=>c.abort(),8000);try{const r=await fetch(`${API_BASE}${path}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body),signal:c.signal,cache:"no-store"});const p=await r.json().catch(()=>({}));if(!r.ok)throw new Error(p.error?.message||"目前無法登入");return p;}finally{clearTimeout(timer)}}
  form.addEventListener("submit",async e=>{e.preventDefault();if(!window.PublicKeyCredential){message.textContent="此瀏覽器不支援 Passkey。";return}submit.disabled=true;message.textContent="正在驗證帳號…";try{const s=await request("/auth/login/begin",{username:form.elements.account.value.trim(),password:form.elements.password.value});form.elements.password.value="";message.textContent=s.ceremony==="registration"?"請使用 Windows Hello 綁定這台裝置。":"請使用已綁定的 Passkey。";const publicKey=prepare(s.public_key,s.ceremony);const c=s.ceremony==="registration"?await navigator.credentials.create({publicKey}):await navigator.credentials.get({publicKey});const result=await request("/auth/login/complete",{flow_id:s.flow_id,credential:serialize(c)});sessionStorage.setItem("taiwan_stock_access_token",result.access_token);sessionStorage.setItem("taiwan_stock_account",JSON.stringify(result.user));message.textContent=`登入成功：${result.user.username}（已使用 Passkey）`;}catch(err){message.textContent=err.name==="NotAllowedError"?"Passkey 驗證已取消或逾時。":(err.message||"目前無法登入");}finally{submit.disabled=false}});
})();
